name: Setup
description: Setup Node.js and install dependencies
inputs:
  NPM_TOKEN:
    description: 'NPM Token'
    required: true

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        version: 10.4.1
        run_install: false

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc

    - name: Ensure npm supports trusted publishing
      shell: bash
      run: |
        npm install -g npm@^11.5.1
        node -v
        npm -v
        pnpm -v

    - name: Get pnpm store directory
      id: get-pnpm-store-path
      shell: bash
      run: echo "store_path=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

    - name: Cache pnpm store
      uses: actions/cache@v4
      with:
        path: ${{ steps.get-pnpm-store-path.outputs.store_path }}
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.NPM_TOKEN }}
